language: node_js
node_js: "12"
branches:
  only:
    - master
install:
  - npm install -g codecov
  - npm install -g coveralls
  - cd client && yarn
scripts:
  - npm run coveralls
cache:
  directories:
    - node_modules
#notifications:
 # webhooks: 
  #  - https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
